export const AUDIO_CONFIG = {
  musicSrc: 'audio/chapter-01-bar.mp3',
  musicVolume: 0.09,
  fadeInMs: 1000,
  fadeOutMs: 900,
  loop: true,
  advanceClickSrc: 'audio/line-click.mp3',
  advanceClickVolume: 0.014,
  choiceClickSrc: 'audio/choice-click.mp3',
  choiceClickVolume: 0.022,
  smokeInhaleSrc: 'audio/smoke-inhale.wav',
  smokeInhaleVolume: 0.14,
  smokeExhaleSrc: 'audio/smoke-exhale.wav',
  smokeExhaleVolume: 0.22,
  doorSrc: 'audio/bar-door.wav',
  doorVolume: 0.12,
  shuttleSrc: 'audio/shuttle-pass.mp3',
  shuttleVolume: 0.38,
  fightEndFlashSrc: 'audio/fight-end-flash.wav',
  fightEndFlashVolume: 0.16,
  aftermathDropSrc: 'audio/aftermath-drop.wav',
  aftermathDropVolume: 0.11,
  memoryRealignSrc: 'audio/memory-realign.wav',
  memoryRealignVolume: 0.1,
  sampledStoryEffects: {
    impact_early: { src: 'audio/fight/first-impact.wav', volume: 0.045 },
    'visitor-step-01': { src: 'audio/fight/visitor-step-01.wav', volume: 0.065 },
    'visitor-step-02': { src: 'audio/fight/visitor-step-02.wav', volume: 0.06 },
    'stand-up': { src: 'audio/fight/stand-up.wav', volume: 0.075 },
    'chair-scrape': { src: 'audio/fight/chair-scrape.wav', volume: 0.055 },
    'body-hit-heavy': { src: 'audio/fight/body-hit-heavy.wav', volume: 0.105 },
    'body-fall': { src: 'audio/fight/body-fall.wav', volume: 0.09 },
    'body-fall-heavy': { src: 'audio/fight/body-fall-heavy.wav', volume: 0.095 },
    body_impact: { src: 'audio/fight/body-impact.mp3', volume: 0.075 },
    'knee-fall': { src: 'audio/fight/knee-fall.wav', volume: 0.08 },
    'knee-contact': { src: 'audio/fight/knee-fall.wav', volume: 0.042 },
    'shoulder-contact': { src: 'audio/fight/shoulder-contact.wav', volume: 0.05 },
    'strike-swipe': { src: 'audio/fight/strike-swipe.wav', volume: 0.06 },
    impact_distant: { src: 'audio/fight/impact-distant.mp3', volume: 0.05 },
    glass_impact: { src: 'audio/fight/glass-impact.mp3', volume: 0.055 },
    glass_fall: { src: 'audio/fight/glass-fall.mp3', volume: 0.045 },
    can_roll: { src: 'audio/fight/can-roll.mp3', volume: 0.055 },
    'can-crush': { src: 'audio/fight/can-crush.wav', volume: 0.06 },
    'can-toe-contact': { src: 'audio/fight/can-toe-contact.wav', volume: 0.055 },
    'shoe-slip': { src: 'audio/fight/shoe-slip.wav', volume: 0.28 },
    'pain-pulse': { src: 'audio/fight/pain-pulse.wav', volume: 0.07 },
    'memory-whoosh-short': { src: 'audio/fight/memory-whoosh-short.wav', volume: 0.07 },
    'memory-whoosh-sharp': { src: 'audio/fight/memory-whoosh-sharp.wav', volume: 0.065 },
    'memory-whoosh-deep': { src: 'audio/fight/memory-whoosh-deep.wav', volume: 0.075 },
    'hollow-01': { src: 'audio/fight/hollow-01.wav', volume: 0.084 },
    'hollow-02': { src: 'audio/fight/hollow-02.wav', volume: 0.086 },
    'hollow-03': { src: 'audio/fight/hollow-03.wav', volume: 0.09 },
  },
} as const;
